from enum import Enum

class EscolaridadeEnum(str, Enum):
    ANALFABETO = "Analfabeto"
    FUNDAMENTAL_INCOMPLETO = "Fundamental Incompleto"
    FUNDAMENTAL_COMPLETO = "Fundamental Completo"
    MEDIO_INCOMPLETO = "Médio Incompleto"
    MEDIO_COMPLETO = "Médio Completo"
    SUPERIOR_INCOMPLETO = "Superior Incompleto"
    SUPERIOR_COMPLETO = "Superior Completo"
    MESTRADO = "Mestrado"
    DOUTORADO = "Doutorado"

class SexoEnum(str, Enum):
    MASCULINO = "Masculino"
    FEMININO = "Feminino"

class RacaEnum(str, Enum):
    INDIGENA = "Indígena"
    BRANCA = "Branca"
    PRETA = "Preta"
    AMARELA = "Amarela"
    PARDA = "Parda"
    NAO_INFORMADO = "Não Informado"

class TamanhoEmpresaEnum(str, Enum):
    ZERO = "Zero funcionários"
    ATE_4 = "De 1 a 4 funcionários"
    DE_5_A_9 = "De 5 a 9 funcionários"
    DE_10_A_19 = "De 10 a 19 funcionários"
    DE_20_A_49 = "De 20 a 49 funcionários"
    DE_50_A_99 = "De 50 a 99 funcionários"
    DE_100_A_249 = "De 100 a 249 funcionários"
    DE_250_A_499 = "De 250 a 499 funcionários"
    DE_500_A_999 = "De 500 a 999 funcionários"
    MAIS_DE_1000 = "1000 ou mais funcionários"

class SetorIbgeEnum(str, Enum):
    EXTRA_MINERAL = "Extrativa Mineral"
    IND_METALURGICA = "Indústria Metalúrgica"
    IND_MECANICA = "Indústria Mecânica"
    IND_ELETRICA = "Indústria Elétrica e Comunicação"
    IND_TRANSPORTE = "Material de Transporte"
    IND_MADEIRA_MOB = "Madeira e Mobiliário"
    IND_PAPEL_GRAF = "Papel, Papelão e Gráfica"
    IND_BORRACHA_COURO = "Borracha, Fumo, Couros"
    IND_QUIMICA = "Indústria Química"
    IND_TEXTIL = "Indústria Têxtil"
    IND_CALCADOS = "Indústria de Calçados"
    IND_ALIMENTOS = "Alimentos e Bebidas"
    SERV_UTIL_PUB = "Serviços de Utilidade Pública"
    CONSTRUCAO_CIVIL = "Construção Civil"
    COMERCIO_VAREJISTA = "Comércio Varejista"
    COMERCIO_ATACADISTA = "Comércio Atacadista"
    INST_FINANCEIRAS = "Instituições Financeiras (Bancos)"
    ADM_IMOVEIS = "Adm de Imóveis e Valores Mob."
    TRANSPORTES = "Transportes e Comunicações"
    SERV_ALOJ_ALIM = "Alojamento e Alimentação"
    SERV_MEDICOS = "Médicos, Odontológicos e Veterinários"
    ENSINO = "Ensino"
    ADM_PUBLICA = "Administração Pública"
    AGRICULTURA = "Agricultura e Pesca"

class CargoEnum(str, Enum):
    ADMINISTRADOR_DE_BANCO_DE_DADOS = "Administrador de banco de dados"
    ADMINISTRADOR_DE_REDES = "Administrador de redes"
    ADMINISTRADOR_DE_SISTEMAS_OPERACIONAIS = "Administrador de sistemas operacionais"
    ADMINISTRADOR_EM_SEGURANÇA_DA_INFORMAÇÃO = "Administrador em segurança da informação"
    ANALISTA_DE_DESENVOLVIMENTO_DE_SISTEMAS = "Analista de desenvolvimento de sistemas"
    ANALISTA_DE_E_COMMERCE = "Analista de e-commerce"
    ANALISTA_DE_NEGÓCIOS = "Analista de negócios"
    ANALISTA_DE_PESQUISA_DE_MERCADO = "Analista de pesquisa de mercado"
    ANALISTA_DE_REDES_E_DE_COMUNICAÇÃO_DE_DADOS = "Analista de redes e de comunicação de dados"
    ANALISTA_DE_RISCOS = "Analista de riscos"
    ANALISTA_DE_SISTEMAS_DE_AUTOMAÇÃO = "Analista de sistemas de automação"
    ANALISTA_DE_SUPORTE_COMPUTACIONAL = "Analista de suporte computacional"
    ANALISTA_DE_TESTES_DE_TECNOLOGIA_DA_INFORMAÇÃO = "Analista de testes de tecnologia da informação"
    ARQUITETO_DE_SOLUÇÕES_DE_TECNOLOGIA_DA_INFORMAÇÃO = "Arquiteto de soluções de tecnologia da informação"
    CIENTISTA_DE_DADOS = "Cientista de dados"
    DESENHISTA_INDUSTRIAL_GRÁFICO_DESIGNER_GRÁFICO = "Desenhista industrial gráfico (designer gráfico)"
    DESENVOLVEDOR_DE_MULTIMÍDIA = "Desenvolvedor de multimídia"
    DESENVOLVEDOR_DE_SISTEMAS_DE_TECNOLOGIA_DA_INFORMAÇÃO_TÉCNICO = "Desenvolvedor de sistemas de tecnologia da informação (técnico)"
    DESENVOLVEDOR_WEB_TÉCNICO = "Desenvolvedor web (técnico)"
    DIRETOR_DE_TECNOLOGIA_DA_INFORMAÇÃO = "Diretor de tecnologia da informação"
    ENGENHEIRO_DE_APLICATIVOS_EM_COMPUTAÇÃO = "Engenheiro de aplicativos em computação"
    ENGENHEIRO_DE_EQUIPAMENTOS_EM_COMPUTAÇÃO = "Engenheiro de equipamentos em computação"
    ENGENHEIRO_DE_REDES_DE_COMUNICAÇÃO = "Engenheiro de redes de comunicação"
    ENGENHEIROS_DE_SISTEMAS_OPERACIONAIS_EM_COMPUTAÇÃO = "Engenheiros de sistemas operacionais em computação"
    ESPECIALISTA_EM_PESQUISA_OPERACIONAL = "Especialista em pesquisa operacional"
    ESTATÍSTICO = "Estatístico"
    ESTATÍSTICO_ESTATÍSTICA_APLICADA = "Estatístico (estatística aplicada)"
    ESTATÍSTICO_TEÓRICO = "Estatístico teórico"
    GERENTE_DE_INFRAESTRUTURA_DE_TECNOLOGIA_DA_INFORMAÇÃO = "Gerente de infraestrutura de tecnologia da informação"
    GERENTE_DE_OPERAÇÃO_DE_TECNOLOGIA_DA_INFORMAÇÃO = "Gerente de operação de tecnologia da informação"
    GERENTE_DE_PROJETOS_DE_TECNOLOGIA_DA_INFORMAÇÃO = "Gerente de projetos de tecnologia da informação"
    GERENTE_DE_SEGURANÇA_DA_INFORMAÇÃO = "Gerente de segurança da informação"
    GERENTE_DE_SUPORTE_TÉCNICO_DE_TECNOLOGIA_DA_INFORMAÇÃO = "Gerente de suporte técnico de tecnologia da informação"
    OFICIAL_DE_PROTEÇÃO_DE_DADOS_PESSOAIS_DPO = "Oficial de proteção de dados pessoais (dpo)"
    PESQUISADOR_EM_CIÊNCIAS_DA_COMPUTAÇÃO_E_INFORMÁTICA = "Pesquisador em ciências da computação e informática"
    PROFESSOR_DE_COMPUTAÇÃO_NO_ENSINO_SUPERIOR = "Professor de computação (no ensino superior)"
    TECNÓLOGO_EM_GESTÃO_DA_TECNOLOGIA_DA_INFORMAÇÃO = "Tecnólogo em gestão da tecnologia da informação"
    TÉCNICO_DE_COMUNICAÇÃO_DE_DADOS = "Técnico de comunicação de dados"
    TÉCNICO_DE_REDE_TELECOMUNICAÇÕES = "Técnico de rede (telecomunicações)"
    TÉCNICO_DE_SUPORTE_AO_USUÁRIO_DE_TECNOLOGIA_DA_INFORMAÇÃO = "Técnico de suporte ao usuário de tecnologia da informação"
    TÉCNICO_EM_MANUTENÇÃO_DE_EQUIPAMENTOS_DE_INFORMÁTICA = "Técnico em manutenção de equipamentos de informática"